-- Cuánto de cada cobro se aplicó a cada alquiler. Antes el reporte lo deducía
-- del texto del movimiento de caja ("Pago de alquileres #12, #13 ..."), lo que
-- mezclaba #12 con #120, repetía el monto completo en cada alquiler de un cobro
-- compartido y perdía los números cortados por el límite de 50 caracteres.
--
-- Se registra desde esta versión en adelante; los cobros anteriores se siguen
-- mostrando a partir del texto (ver Alquiler.getPagosReporte).
CREATE TABLE IF NOT EXISTS public.alquilerpago (
  "AlquilerPagoId" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "AlquilerId" integer NOT NULL
    REFERENCES public.alquiler ("AlquilerId") ON DELETE CASCADE,
  -- Movimiento de caja del cobro; nulo si se cobró sin registrar en caja.
  -- Si se borra el movimiento, el pago deja de figurar en el reporte
  "RegistroDiarioCajaId" integer
    REFERENCES public.registrodiariocaja ("RegistroDiarioCajaId") ON DELETE CASCADE,
  "AlquilerPagoFecha" date NOT NULL DEFAULT CURRENT_DATE,
  -- Importe aplicado al saldo del alquiler (base, sin recargo de tarjeta)
  "AlquilerPagoMonto" bigint NOT NULL CHECK ("AlquilerPagoMonto" > 0)
);

CREATE INDEX IF NOT EXISTS alquilerpago_alquilerid_idx
  ON public.alquilerpago ("AlquilerId");
CREATE INDEX IF NOT EXISTS alquilerpago_registrodiariocajaid_idx
  ON public.alquilerpago ("RegistroDiarioCajaId");
