-- ============================================================================
-- Esquema de decorpar en PostgreSQL
-- Traducido del esquema MySQL/MariaDB original. Parte de la salida de GeneXus.
--
-- Convenciones de tipos (las mismas que uso la rama alquiler-prendas):
--   int(11)        -> integer
--   mediumint(9)   -> integer
--   smallint(6)    -> smallint
--   bigint(20)     -> bigint
--   decimal(11,2)  -> numeric(11,2)
--   char(n)        -> character varying(n)   (PG rellena char(n) con espacios)
--   varchar(n)     -> character varying(n)
--   tinyint(1)     -> smallint               (la app usa 0/1, no booleanos)
--   longblob       -> bytea
--   AUTO_INCREMENT -> GENERATED BY DEFAULT AS IDENTITY
--
-- Los identificadores van entre comillas para conservar el CamelCase; la capa
-- de traduccion de api/config/db.js se apoya en eso.
--
-- Uso:
--   psql -U postgres -d decorpar -f db/postgres/01_schema.sql
-- ============================================================================

-- --- Tablas sin dependencias -------------------------------------------------

CREATE TABLE almacen (
    "AlmacenId"     integer NOT NULL,
    "AlmacenNombre" character varying(30) DEFAULT '' NOT NULL
);

CREATE TABLE caja (
    "CajaId"          integer NOT NULL,
    "CajaDescripcion" character varying(30) DEFAULT '' NOT NULL,
    "CajaMonto"       bigint DEFAULT 0 NOT NULL
);

CREATE TABLE local (
    "LocalId"        integer NOT NULL,
    "LocalNombre"    character varying(30) DEFAULT '' NOT NULL,
    "LocalTelefono"  character varying(20) DEFAULT '' NOT NULL,
    "LocalCelular"   character varying(20) DEFAULT '' NOT NULL,
    "LocalDireccion" character varying(1024) DEFAULT '' NOT NULL
);

CREATE TABLE menu (
    "MenuId"     character varying(25) DEFAULT '' NOT NULL,
    "MenuNombre" character varying(30) DEFAULT '' NOT NULL
);

CREATE TABLE perfil (
    "PerfilId"          integer NOT NULL,
    "PerfilDescripcion" character varying(30) DEFAULT '' NOT NULL
);

CREATE TABLE proveedor (
    "ProveedorId"        integer NOT NULL,
    "ProveedorRUC"       character varying(20) DEFAULT '' NOT NULL,
    "ProveedorNombre"    character varying(30) DEFAULT '' NOT NULL,
    "ProveedorDireccion" character varying(1024) DEFAULT '' NOT NULL,
    "ProveedorTelefono"  character varying(20) DEFAULT '' NOT NULL
);

CREATE TABLE tipogasto (
    "TipoGastoId"          integer NOT NULL,
    "TipoGastoDescripcion" character varying(30) DEFAULT '' NOT NULL,
    "TipoGastoCantGastos"  smallint DEFAULT 0 NOT NULL
);

-- --- Tablas dependientes -----------------------------------------------------

CREATE TABLE usuario (
    "UsuarioId"         character varying(25) DEFAULT '' NOT NULL,
    "UsuarioContrasena" character varying(100) DEFAULT '' NOT NULL,
    "UsuarioNombre"     character varying(30) DEFAULT '' NOT NULL,
    "UsuarioApellido"   character varying(30) DEFAULT '' NOT NULL,
    "UsuarioCorreo"     character varying(100) DEFAULT '' NOT NULL,
    "UsuarioIsAdmin"    character varying(1) DEFAULT '' NOT NULL,
    "UsuarioEstado"     character varying(1) DEFAULT '' NOT NULL,
    "LocalId"           integer DEFAULT 0 NOT NULL
);

CREATE TABLE clientes (
    "ClienteId"        integer NOT NULL,
    "ClienteRUC"       character varying(20) DEFAULT '' NOT NULL,
    "ClienteNombre"    character varying(30) DEFAULT '' NOT NULL,
    "ClienteApellido"  character varying(30) DEFAULT '' NOT NULL,
    "ClienteDireccion" character varying(1024) DEFAULT '' NOT NULL,
    "ClienteTelefono"  character varying(20) DEFAULT '' NOT NULL,
    "ClienteTipo"      character varying(2) DEFAULT '' NOT NULL,
    "UsuarioId"        character varying(25)
);

CREATE TABLE usuarioperfil (
    "UsuarioId" character varying(25) DEFAULT '' NOT NULL,
    "PerfilId"  integer DEFAULT 0 NOT NULL
);

CREATE TABLE perfilmenu (
    "PerfilId"      integer DEFAULT 0 NOT NULL,
    "MenuId"        character varying(25) DEFAULT '' NOT NULL,
    "puedeCrear"    smallint DEFAULT 0 NOT NULL,
    "puedeEditar"   smallint DEFAULT 0 NOT NULL,
    "puedeEliminar" smallint DEFAULT 0 NOT NULL,
    "puedeLeer"     smallint DEFAULT 0 NOT NULL
);

CREATE TABLE tipogastogrupo (
    "TipoGastoId"               integer DEFAULT 0 NOT NULL,
    "TipoGastoGrupoId"          smallint DEFAULT 0 NOT NULL,
    "TipoGastoGrupoDescripcion" character varying(30) DEFAULT '' NOT NULL
);

CREATE TABLE producto (
    "ProductoId"                   integer NOT NULL,
    "ProductoCodigo"               character varying(40) DEFAULT '' NOT NULL,
    "ProductoNombre"               character varying(50) DEFAULT '' NOT NULL,
    "ProductoPrecioVenta"          bigint DEFAULT 0 NOT NULL,
    "ProductoPrecioVentaMayorista" bigint DEFAULT 0 NOT NULL,
    "ProductoPrecioUnitario"       bigint DEFAULT 0 NOT NULL,
    "ProductoPrecioPromedio"       numeric(11,2) DEFAULT 0 NOT NULL,
    "ProductoStock"                integer DEFAULT 0 NOT NULL,
    "ProductoStockUnitario"        integer DEFAULT 0 NOT NULL,
    "ProductoCantidadCaja"         integer DEFAULT 0 NOT NULL,
    "ProductoIVA"                  smallint DEFAULT 0 NOT NULL,
    "ProductoStockMinimo"          integer DEFAULT 0 NOT NULL,
    "ProductoImagen"               bytea DEFAULT '\x'::bytea NOT NULL,
    "ProductoImagen_GXI"           character varying(2048),
    "LocalId"                      integer DEFAULT 0 NOT NULL
);

CREATE TABLE productoalmacen (
    "ProductoId"                   integer DEFAULT 0 NOT NULL,
    "AlmacenId"                    integer DEFAULT 0 NOT NULL,
    "ProductoAlmacenStock"         integer DEFAULT 0 NOT NULL,
    "ProductoAlmacenStockUnitario" integer DEFAULT 0 NOT NULL
);

CREATE TABLE combo (
    "ComboId"          integer NOT NULL,
    "ComboDescripcion" character varying(50) DEFAULT '' NOT NULL,
    "ProductoId"       integer DEFAULT 0 NOT NULL,
    "ComboCantidad"    integer DEFAULT 0 NOT NULL,
    "ComboPrecio"      bigint DEFAULT 0 NOT NULL
);

CREATE TABLE registrodiariocaja (
    "RegistroDiarioCajaId"      integer NOT NULL,
    "CajaId"                    integer DEFAULT 0 NOT NULL,
    "RegistroDiarioCajaFecha"   date NOT NULL,
    "TipoGastoId"               integer DEFAULT 0 NOT NULL,
    "TipoGastoGrupoId"          smallint DEFAULT 0 NOT NULL,
    "RegistroDiarioCajaDetalle" character varying(50) DEFAULT '' NOT NULL,
    "RegistroDiarioCajaMonto"   bigint DEFAULT 0 NOT NULL,
    "UsuarioId"                 character varying(25),
    -- Venta que origino el movimiento. Agregada al sacar GeneXus: antes la
    -- anulacion borraba los movimientos comparando el texto del detalle, y al
    -- reiniciarse la numeracion de ventas eso alcanzaba filas historicas de
    -- otras cajas. Las filas viejas quedan en NULL y nunca se tocan.
    "VentaId"                   integer
);

CREATE TABLE venta (
    "VentaId"                integer NOT NULL,
    "VentaFecha"             date NOT NULL,
    "ClienteId"              integer DEFAULT 0 NOT NULL,
    "AlmacenId"              integer DEFAULT 0 NOT NULL,
    "VentaTipo"              character varying(2) DEFAULT '' NOT NULL,
    "VentaPagoTipo"          character varying(1) DEFAULT '' NOT NULL,
    "VentaCantidadProductos" smallint DEFAULT 0 NOT NULL,
    "VentaUsuario"           character varying(25) DEFAULT '' NOT NULL,
    "Total"                  bigint DEFAULT 0 NOT NULL,
    "VentaEntrega"           bigint DEFAULT 0 NOT NULL
);

CREATE TABLE ventaproducto (
    "VentaId"                     integer DEFAULT 0 NOT NULL,
    "VentaProductoId"             smallint DEFAULT 0 NOT NULL,
    "ProductoId"                  integer DEFAULT 0 NOT NULL,
    "VentaProductoPrecioPromedio" bigint DEFAULT 0 NOT NULL,
    "VentaProductoCantidad"       integer DEFAULT 0 NOT NULL,
    "VentaProductoPrecio"         bigint DEFAULT 0 NOT NULL,
    "VentaProductoPrecioTotal"    bigint DEFAULT 0 NOT NULL,
    "VentaProductoUnitario"       character varying(1) DEFAULT '' NOT NULL
);

CREATE TABLE ventacredito (
    "VentaCreditoId"       integer NOT NULL,
    "VentaId"              integer DEFAULT 0 NOT NULL,
    "VentaCreditoPagoCant" smallint DEFAULT 0 NOT NULL
);

CREATE TABLE ventacreditopago (
    "VentaCreditoId"        integer DEFAULT 0 NOT NULL,
    "VentaCreditoPagoId"    smallint DEFAULT 0 NOT NULL,
    "VentaCreditoPagoFecha" date NOT NULL,
    "VentaCreditoPagoMonto" bigint DEFAULT 0 NOT NULL
);

CREATE TABLE compra (
    "CompraId"           integer NOT NULL,
    "CompraFecha"        date NOT NULL,
    "ProveedorId"        integer DEFAULT 0 NOT NULL,
    "UsuarioId"          character varying(25),
    "CompraFactura"      bigint DEFAULT 0 NOT NULL,
    "CompraTipo"         character varying(2) DEFAULT '' NOT NULL,
    "CompraPagoCompleto" character varying(1) DEFAULT '' NOT NULL,
    "CompraEntrega"      numeric(11,2) DEFAULT 0 NOT NULL
);

CREATE TABLE compraproducto (
    "CompraId"                     integer DEFAULT 0 NOT NULL,
    "ProductoId"                   integer DEFAULT 0 NOT NULL,
    "CompraProductoCantidad"       integer DEFAULT 0 NOT NULL,
    "CompraProductoCantidadUnidad" character varying(1) DEFAULT '' NOT NULL,
    "CompraProductoBonificacion"   integer DEFAULT 0 NOT NULL,
    "CompraProductoPrecio"         numeric(11,2) DEFAULT 0 NOT NULL,
    "AlmacenOrigenId"              integer DEFAULT 0 NOT NULL
);

CREATE TABLE facturacredito (
    "FacturaCreditoId"       integer NOT NULL,
    "CompraId"               integer DEFAULT 0 NOT NULL,
    "FacturaCreditoPagoCant" smallint DEFAULT 0 NOT NULL
);

CREATE TABLE facturacreditopago (
    "FacturaCreditoId"        integer DEFAULT 0 NOT NULL,
    "FacturaCreditoPagoId"    smallint DEFAULT 0 NOT NULL,
    "FacturaCreditoPagoFecha" date NOT NULL,
    "FacturaCreditoPagoMonto" bigint DEFAULT 0 NOT NULL
);

CREATE TABLE traslado (
    "TrasladoId"       integer NOT NULL,
    "TrasladoFecha"    date NOT NULL,
    "ProductoId"       integer DEFAULT 0 NOT NULL,
    "TrasladoCantidad" integer DEFAULT 0 NOT NULL,
    "AlmacenOrigenId"  integer DEFAULT 0 NOT NULL,
    "AlmacenDestinoId" integer DEFAULT 0 NOT NULL,
    "UsuarioId"        character varying(25)
);

-- --- Claves primarias --------------------------------------------------------

ALTER TABLE almacen            ADD CONSTRAINT almacen_pkey            PRIMARY KEY ("AlmacenId");
ALTER TABLE caja               ADD CONSTRAINT caja_pkey               PRIMARY KEY ("CajaId");
ALTER TABLE local              ADD CONSTRAINT local_pkey              PRIMARY KEY ("LocalId");
ALTER TABLE menu               ADD CONSTRAINT menu_pkey               PRIMARY KEY ("MenuId");
ALTER TABLE perfil             ADD CONSTRAINT perfil_pkey             PRIMARY KEY ("PerfilId");
ALTER TABLE proveedor          ADD CONSTRAINT proveedor_pkey          PRIMARY KEY ("ProveedorId");
ALTER TABLE tipogasto          ADD CONSTRAINT tipogasto_pkey          PRIMARY KEY ("TipoGastoId");
ALTER TABLE usuario            ADD CONSTRAINT usuario_pkey            PRIMARY KEY ("UsuarioId");
ALTER TABLE clientes           ADD CONSTRAINT clientes_pkey           PRIMARY KEY ("ClienteId");
ALTER TABLE usuarioperfil      ADD CONSTRAINT usuarioperfil_pkey      PRIMARY KEY ("UsuarioId", "PerfilId");
ALTER TABLE perfilmenu         ADD CONSTRAINT perfilmenu_pkey         PRIMARY KEY ("PerfilId", "MenuId");
ALTER TABLE tipogastogrupo     ADD CONSTRAINT tipogastogrupo_pkey     PRIMARY KEY ("TipoGastoId", "TipoGastoGrupoId");
ALTER TABLE producto           ADD CONSTRAINT producto_pkey           PRIMARY KEY ("ProductoId");
ALTER TABLE productoalmacen    ADD CONSTRAINT productoalmacen_pkey    PRIMARY KEY ("ProductoId", "AlmacenId");
ALTER TABLE combo              ADD CONSTRAINT combo_pkey              PRIMARY KEY ("ComboId");
ALTER TABLE registrodiariocaja ADD CONSTRAINT registrodiariocaja_pkey PRIMARY KEY ("RegistroDiarioCajaId");
ALTER TABLE venta              ADD CONSTRAINT venta_pkey              PRIMARY KEY ("VentaId");
ALTER TABLE ventaproducto      ADD CONSTRAINT ventaproducto_pkey      PRIMARY KEY ("VentaId", "VentaProductoId");
ALTER TABLE ventacredito       ADD CONSTRAINT ventacredito_pkey       PRIMARY KEY ("VentaCreditoId");
ALTER TABLE ventacreditopago   ADD CONSTRAINT ventacreditopago_pkey   PRIMARY KEY ("VentaCreditoId", "VentaCreditoPagoId");
ALTER TABLE compra             ADD CONSTRAINT compra_pkey             PRIMARY KEY ("CompraId");
ALTER TABLE compraproducto     ADD CONSTRAINT compraproducto_pkey     PRIMARY KEY ("CompraId", "ProductoId");
ALTER TABLE facturacredito     ADD CONSTRAINT facturacredito_pkey     PRIMARY KEY ("FacturaCreditoId");
ALTER TABLE facturacreditopago ADD CONSTRAINT facturacreditopago_pkey PRIMARY KEY ("FacturaCreditoId", "FacturaCreditoPagoId");
ALTER TABLE traslado           ADD CONSTRAINT traslado_pkey           PRIMARY KEY ("TrasladoId");

-- productoalmacen necesita un unico sobre (ProductoId, AlmacenId) para que
-- compraproducto y traslado puedan referenciarlo: ya lo cubre su PK.

-- --- Autonumeracion ----------------------------------------------------------
-- Nota: en MySQL venta."VentaId" NO era AUTO_INCREMENT (GeneXus generaba el
-- numero). Aca si lleva identity, que es lo que permite sacar GeneXus.

ALTER TABLE almacen            ALTER COLUMN "AlmacenId"            ADD GENERATED BY DEFAULT AS IDENTITY;
ALTER TABLE caja               ALTER COLUMN "CajaId"               ADD GENERATED BY DEFAULT AS IDENTITY;
ALTER TABLE local              ALTER COLUMN "LocalId"              ADD GENERATED BY DEFAULT AS IDENTITY;
ALTER TABLE perfil             ALTER COLUMN "PerfilId"             ADD GENERATED BY DEFAULT AS IDENTITY;
ALTER TABLE proveedor          ALTER COLUMN "ProveedorId"          ADD GENERATED BY DEFAULT AS IDENTITY;
ALTER TABLE tipogasto          ALTER COLUMN "TipoGastoId"          ADD GENERATED BY DEFAULT AS IDENTITY;
ALTER TABLE clientes           ALTER COLUMN "ClienteId"            ADD GENERATED BY DEFAULT AS IDENTITY;
ALTER TABLE producto           ALTER COLUMN "ProductoId"           ADD GENERATED BY DEFAULT AS IDENTITY;
ALTER TABLE combo              ALTER COLUMN "ComboId"              ADD GENERATED BY DEFAULT AS IDENTITY;
ALTER TABLE registrodiariocaja ALTER COLUMN "RegistroDiarioCajaId" ADD GENERATED BY DEFAULT AS IDENTITY;
ALTER TABLE venta              ALTER COLUMN "VentaId"              ADD GENERATED BY DEFAULT AS IDENTITY;
ALTER TABLE ventacredito       ALTER COLUMN "VentaCreditoId"       ADD GENERATED BY DEFAULT AS IDENTITY;
ALTER TABLE compra             ALTER COLUMN "CompraId"             ADD GENERATED BY DEFAULT AS IDENTITY;
ALTER TABLE facturacredito     ALTER COLUMN "FacturaCreditoId"     ADD GENERATED BY DEFAULT AS IDENTITY;
ALTER TABLE traslado           ALTER COLUMN "TrasladoId"           ADD GENERATED BY DEFAULT AS IDENTITY;

-- --- Claves foraneas ---------------------------------------------------------

ALTER TABLE usuario            ADD CONSTRAINT "IUSUARIO1"            FOREIGN KEY ("LocalId")            REFERENCES local ("LocalId");
ALTER TABLE clientes           ADD CONSTRAINT "ICLIENTES1"           FOREIGN KEY ("UsuarioId")          REFERENCES usuario ("UsuarioId");
ALTER TABLE usuarioperfil      ADD CONSTRAINT "IUSUARIOPERFIL1"      FOREIGN KEY ("PerfilId")           REFERENCES perfil ("PerfilId");
ALTER TABLE usuarioperfil      ADD CONSTRAINT "IUSUARIOPERFIL2"      FOREIGN KEY ("UsuarioId")          REFERENCES usuario ("UsuarioId");
ALTER TABLE perfilmenu         ADD CONSTRAINT "IPERFILMENU1"         FOREIGN KEY ("MenuId")             REFERENCES menu ("MenuId");
ALTER TABLE perfilmenu         ADD CONSTRAINT "IPERFILMENU2"         FOREIGN KEY ("PerfilId")           REFERENCES perfil ("PerfilId");
ALTER TABLE tipogastogrupo     ADD CONSTRAINT "ITIPOGASTOGRUPO1"     FOREIGN KEY ("TipoGastoId")        REFERENCES tipogasto ("TipoGastoId");
ALTER TABLE producto           ADD CONSTRAINT "IPRODUCTO1"           FOREIGN KEY ("LocalId")            REFERENCES local ("LocalId");
ALTER TABLE productoalmacen    ADD CONSTRAINT "IPRODUCTOALMACEN1"    FOREIGN KEY ("AlmacenId")          REFERENCES almacen ("AlmacenId");
ALTER TABLE productoalmacen    ADD CONSTRAINT "IPRODUCTOALMACEN2"    FOREIGN KEY ("ProductoId")         REFERENCES producto ("ProductoId");
ALTER TABLE combo              ADD CONSTRAINT "ICOMBO1"              FOREIGN KEY ("ProductoId")         REFERENCES producto ("ProductoId");
ALTER TABLE registrodiariocaja ADD CONSTRAINT "IREGISTRODIARIOCAJA1" FOREIGN KEY ("TipoGastoId", "TipoGastoGrupoId") REFERENCES tipogastogrupo ("TipoGastoId", "TipoGastoGrupoId");
ALTER TABLE registrodiariocaja ADD CONSTRAINT "IREGISTRODIARIOCAJA2" FOREIGN KEY ("CajaId")             REFERENCES caja ("CajaId");
ALTER TABLE registrodiariocaja ADD CONSTRAINT "IREGISTRODIARIOCAJA3" FOREIGN KEY ("UsuarioId")          REFERENCES usuario ("UsuarioId");
ALTER TABLE venta              ADD CONSTRAINT "IVENTA1"              FOREIGN KEY ("ClienteId")          REFERENCES clientes ("ClienteId");
ALTER TABLE venta              ADD CONSTRAINT "IVENTA2"              FOREIGN KEY ("AlmacenId")          REFERENCES almacen ("AlmacenId");
ALTER TABLE ventaproducto      ADD CONSTRAINT "IVENTAPRODUCTO1"      FOREIGN KEY ("ProductoId")         REFERENCES producto ("ProductoId");
ALTER TABLE ventaproducto      ADD CONSTRAINT "IVENTAPRODUCTO2"      FOREIGN KEY ("VentaId")            REFERENCES venta ("VentaId");
ALTER TABLE ventacredito       ADD CONSTRAINT "IVENTACREDITO1"       FOREIGN KEY ("VentaId")            REFERENCES venta ("VentaId");
ALTER TABLE ventacreditopago   ADD CONSTRAINT "IVENTACREDITOPAGO1"   FOREIGN KEY ("VentaCreditoId")     REFERENCES ventacredito ("VentaCreditoId");
ALTER TABLE compra             ADD CONSTRAINT "ICOMPRA1"             FOREIGN KEY ("ProveedorId")        REFERENCES proveedor ("ProveedorId");
ALTER TABLE compra             ADD CONSTRAINT "ICOMPRA2"             FOREIGN KEY ("UsuarioId")          REFERENCES usuario ("UsuarioId");
ALTER TABLE compraproducto     ADD CONSTRAINT "ICOMPRAPRODUCTO1"     FOREIGN KEY ("ProductoId", "AlmacenOrigenId") REFERENCES productoalmacen ("ProductoId", "AlmacenId");
ALTER TABLE compraproducto     ADD CONSTRAINT "ICOMPRAPRODUCTO2"     FOREIGN KEY ("CompraId")           REFERENCES compra ("CompraId");
ALTER TABLE facturacredito     ADD CONSTRAINT "IFACTURACREDITO1"     FOREIGN KEY ("CompraId")           REFERENCES compra ("CompraId");
ALTER TABLE facturacreditopago ADD CONSTRAINT "IFACTURACREDITOPAGO1" FOREIGN KEY ("FacturaCreditoId")   REFERENCES facturacredito ("FacturaCreditoId");
ALTER TABLE traslado           ADD CONSTRAINT "ITRASLADO1"           FOREIGN KEY ("ProductoId", "AlmacenOrigenId")  REFERENCES productoalmacen ("ProductoId", "AlmacenId");
ALTER TABLE traslado           ADD CONSTRAINT "ITRASLADO2"           FOREIGN KEY ("ProductoId", "AlmacenDestinoId") REFERENCES productoalmacen ("ProductoId", "AlmacenId");
ALTER TABLE traslado           ADD CONSTRAINT "ITRASLADO3"           FOREIGN KEY ("UsuarioId")          REFERENCES usuario ("UsuarioId");

-- --- Indices secundarios -----------------------------------------------------

CREATE INDEX "UPRODUCTO"            ON producto ("ProductoNombre");
CREATE INDEX "UCOMPRA"              ON compra ("CompraFecha");
CREATE INDEX "IREGISTRODIARIOCAJA2" ON registrodiariocaja ("CajaId");
CREATE INDEX "IREGISTRODIARIOCAJA_VENTA" ON registrodiariocaja ("VentaId");
CREATE INDEX "IVENTA1_idx"          ON venta ("ClienteId");
CREATE INDEX "IVENTA2_idx"          ON venta ("AlmacenId");
CREATE INDEX "IVENTAPRODUCTO1_idx"  ON ventaproducto ("ProductoId");
