-- ============================================================================
-- Promociones configurables y datos de fidelización del cliente
-- Fecha: 2026-10-07
--
--   clientes          + fecha de nacimiento y vehículo/chapa
--   promocion         cada promoción que configura el cliente
--                       tipo  CU = cumpleaños, FR = cada N servicios
--                       beneficio  D = descuento (%), R = regalo (Gs. 0)
--   promocionproducto productos de una promoción, según su rol:
--                       C = cuentan para llegar a N (solo FR)
--                       B = se pueden dar como beneficio
--   ventapromocion    qué línea de qué venta usó qué promoción. Sirve para
--                     no repetir el beneficio y para reiniciar el conteo.
--
-- Idempotente: se puede volver a correr sin romper nada.
-- En producción correrla con el rol dueño de las tablas (decorpar_app).
-- ============================================================================

BEGIN;

ALTER TABLE clientes ADD COLUMN IF NOT EXISTS "ClienteFechaNacimiento" date;
ALTER TABLE clientes ADD COLUMN IF NOT EXISTS "ClienteVehiculo" varchar(60) DEFAULT '' NOT NULL;

CREATE TABLE IF NOT EXISTS promocion (
    "PromocionId"          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "PromocionNombre"      varchar(60) NOT NULL,
    "PromocionTipo"        varchar(2) NOT NULL CHECK ("PromocionTipo" IN ('CU', 'FR')),
    "PromocionBeneficio"   varchar(1) NOT NULL CHECK ("PromocionBeneficio" IN ('D', 'R')),
    "PromocionDescuento"   numeric(5,2) DEFAULT 0 NOT NULL
                           CHECK ("PromocionDescuento" >= 0 AND "PromocionDescuento" <= 100),
    -- FR: cantidad de servicios que hay que juntar para obtener el beneficio
    "PromocionCantidad"    integer DEFAULT 0 NOT NULL CHECK ("PromocionCantidad" >= 0),
    -- FR: solo cuentan los servicios de los últimos N días (0 = no vencen)
    "PromocionVigenciaDias" integer DEFAULT 0 NOT NULL CHECK ("PromocionVigenciaDias" >= 0),
    -- CU: ventana alrededor del cumpleaños (0 y 0 = solo el día)
    "PromocionDiasAntes"   integer DEFAULT 0 NOT NULL CHECK ("PromocionDiasAntes" >= 0),
    "PromocionDiasDespues" integer DEFAULT 0 NOT NULL CHECK ("PromocionDiasDespues" >= 0),
    "PromocionActiva"      smallint DEFAULT 1 NOT NULL,
    "PromocionMensaje"     varchar(200) DEFAULT '' NOT NULL
);

CREATE TABLE IF NOT EXISTS promocionproducto (
    "PromocionId"          integer NOT NULL REFERENCES promocion ("PromocionId") ON DELETE CASCADE,
    "ProductoId"           integer NOT NULL REFERENCES producto ("ProductoId"),
    "PromocionProductoRol" varchar(1) NOT NULL CHECK ("PromocionProductoRol" IN ('C', 'B')),
    PRIMARY KEY ("PromocionId", "ProductoId", "PromocionProductoRol")
);

CREATE TABLE IF NOT EXISTS ventapromocion (
    "VentaId"                 integer NOT NULL REFERENCES venta ("VentaId"),
    "VentaProductoId"         smallint NOT NULL,
    "PromocionId"             integer NOT NULL REFERENCES promocion ("PromocionId"),
    "ClienteId"               integer NOT NULL REFERENCES clientes ("ClienteId"),
    "VentaPromocionFecha"     date NOT NULL,
    -- Lo que se dejó de cobrar (precio de lista - precio cobrado)
    "VentaPromocionDescuento" bigint DEFAULT 0 NOT NULL,
    PRIMARY KEY ("VentaId", "VentaProductoId")
);

CREATE INDEX IF NOT EXISTS "IVENTAPROMOCION_CLIENTE" ON ventapromocion ("ClienteId", "PromocionId");
CREATE INDEX IF NOT EXISTS "IPROMOCIONPRODUCTO_PRODUCTO" ON promocionproducto ("ProductoId");

COMMIT;
